# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b1b005ed97f5ef5ec939d1a8d4ed2f0bd42d4e0de5146819d28186bd6f5a38e5fd24898f47be1cff2055462712089084926f33c22a1c3bc6539efc1184811c

test:
  secret_key_base: e9e83ccdd40e565c18a353d1a27c3d4bd6defb8e1b29ee340a9e1913318b3b3122b62a17d49a384dc3dc639511b1a8611e43f3c772aae0e81048e4039740d208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
